### ISSUE TITLE
DNS-Setup not working

### ISSUE THREAD

**Issue by bahlo** [bontibon/digitalocean-alpine#1]
Hey, 

when I'm configuring Alpine and running `setup-dis`, it asks for a hostname and name servers.

I tried using the machine name as hostname (`alpine-test`) and DO Nameservers, delimited by Space (`ns1.digitalocean.com ns2.digitalocean.com ns3.digitalocean.com`) or comma, but after restarting networking, I can't `apk update` or `ping google.de`.

**Comment by bontibon** [comment]
1. The networking service needs to be restarted after running `setup-dns` in order for the changes to take place:

        service networking restart

2. The name servers should be DNS servers, not your DO name servers. For example, you can use Google's DNS servers: 8.8.8.8 and 8.8.4.4

**Comment by bahlo** [comment]
I restarted the networking service after setup-dns, but I tried the wrong name servers. 
Thank you very much, it's so obvious now :+1:
