### ISSUE TITLE
Ubuntu 18.04 Support

### ISSUE THREAD

**Issue by Immortalin** [bontibon/digitalocean-alpine#12]
Thanks for building this! Really appreciate the work put in. Do you think you can add support for Ubuntu 18.04?

**Comment by bontibon** [comment]
Have you tried this already? Where does the script fail? What would be the advantage of "officially" supporting Ubuntu 18.04 as the starting droplet image?

**Comment by Immortalin** [comment]
![image](https://user-images.githubusercontent.com/7126128/41823564-72f18e04-77b6-11e8-84e6-c0bb31ad1b62.png)

**Comment by Immortalin** [comment]
Does alpine automatically trigger ssh restart? I am getting connection timed out on login attempts

**Comment by bontibon** [comment]
The `/etc/network/interfaces` file is written by the digitalalpine service that the installer script creates. From your screenshot, it appears to be failing (why I'm not sure).

I'd rather not bother fixing this for a non-Debian based droplet, as I don't want anyone to rely on a base droplet that I do not test myself.

**Comment by Immortalin** [comment]
@bontibon am I correct to assume that the original distro droplet has absolutely no impact on the final alpine creation? i.e. no significant config files will carry over besides ssh?

**Comment by bontibon** [comment]
Correct.

**Comment by Immortalin** [comment]
Almost clean build with Debian:

![image](https://user-images.githubusercontent.com/7126128/41823671-e4c5ab80-77b8-11e8-95a2-2ab2e3cdf78f.png)

**Comment by bontibon** [comment]
eth1 will only be there if IPv6 is enabled.  I'll see if I can prevent that error if IPv6 is disabled.

**Comment by Immortalin** [comment]
Out of curiosity how do you keep alpine automatically updated while it production?

**Comment by bontibon** [comment]
The eth1 should be fixed with 0c9cf56d4cc83537fff9b1bbc0e9444ceaeb69e2.

**Comment by bontibon** [comment]
A current limitation is that IPv6 and private networking must be enabled on droplet creation in order for the digitialocean init script to see it; Digital Ocean's droplet meta file does not updated if IPv6 or private network is added after a droplet is created.
