### ISSUE TITLE
sftp says connection closed and quits

### ISSUE THREAD

**Issue by nickelghost** [bontibon/digitalocean-alpine#17]
Hi, thanks for the great work! I'm using your script for setting up my Droplets. Everything works fine, except for sftp. I tried to access my files on two different Droplets, but I still get the same output:
```
[gabriel@desktop ~]$ sftp root@<ip>
Connection closed.
Connection closed
```
Then it exits. I'm trying to access the droplets with your Alpine from my computer running Arch.

**Comment by nickelghost** [comment]
Thanks for closing the issue. I would like to ask, what would be the way to fix existing installations?

**Comment by bontibon** [comment]
There probably is an `apk` command you can run to reset the `/etc/ssh/sshd_config` file back to the one bundled with the package (which should fix any existing installations), but I do not know what it is off the top of my head.
