### ISSUE TITLE
Droplet create event failed, please try again

### ISSUE THREAD

**Issue by eskin** [bontibon/digitalocean-alpine#2]
Fail to try create new droplet from this snapshot.

Support says:
> It looks like the create events from that snapshot image are failing when attempting to configure the network interfaces.

**Comment by bontibon** [comment]
So you followed the guide, made a snapshot of the droplet, and then attempted to create another droplet from that snapshot. Is that correct?

**Comment by eskin** [comment]
Yes.

**Comment by eskin** [comment]
Any ideas?

**Comment by bontibon** [comment]
> Any ideas?

Not off of the top of my head. If I get around to investigating this, I'll post my findings.

**Comment by bontibon** [comment]
It appears that the new droplet conversion method allows creating a new droplet from a snapshot.  However, the IP address does not get updated for the newly created droplet.

I am making a new ticket for the IP address issue.

**Comment by bontibon** [comment]
Fixed with f8bf681b588b8e6326a37bdfff6bd058f4f70476.

**Comment by eskin** [comment]
cool! thank you!
