### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by gebeer** [bontibon/digitalocean-alpine#5]
Thank you for sharing. I had my droplet up with no problems.
Using this on small RAM droplets, I want to make sure that minimal amount of RAM is blocked by the droplet OS itself.
After installing docker on the droplet and waiting some hours I examined the RAM usage and was surprised that more than 300MB of 512 MB RAM were in use.
Does this alpine install load the whole system into RAM? Is it using the sys install method?
Please clarify. Thank you.

**Comment by bontibon** [comment]
> After installing docker on the droplet and waiting some hours I examined the RAM usage and was surprised that more than 300MB of 512 MB RAM were in use.

I can't speak to that. Maybe docker normally uses that much?

> Does this alpine install load the whole system into RAM? Is it using the sys install method?

Yes, the OS gets installed as "sys".

**Comment by gebeer** [comment]
Thanks for the info.
