### ISSUE TITLE
Great Work! Thank you

### ISSUE THREAD

**Issue by zacksiri** [bontibon/digitalocean-alpine#9]
I've been looking at this repo and it changed from a long instruction to a shell script. Thank you for the hard work! I recently got alpine working on Google Compute Engine and I'm testing a few things out created an aport for it here: https://github.com/artello/aports/tree/develop/gcp/google-compute-engine

I will submit it to official alpine aports once I've tested it abit more.

**Comment by bontibon** [comment]
Thanks for the nice comment.

I am thinking I may have to setup an alpine package for this as well, as  I foresee there being updates to the init script that should be pushed out to existing installs.
